### ISSUE TITLE
OpaqueToken is not a constructor

### ISSUE THREAD

**Issue by Chuvisco88** [Greentube/localize-router-http-loader#2]
Hi there

As I'm a huge fan of the localize-router, it's obvious for me to use the http-loader as well.
Unfortunately I'm receiving an error when starting the app via node.
I already looked a bit into it and from the error I would guess the issue is probably that I'm using Angular 5 (as I have found other repositories with the same error).
As far as I found out Angular 5 does not export OpaqueToken anymore (https://github.com/zefoy/ngx-perfect-scrollbar/issues/113).

```
/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:692
var LOCALIZE_ROUTER_FORROOT_GUARD = new __WEBPACK_IMPORTED_MODULE_0__angular_core__["OpaqueToken"]('LOCALIZE_ROUTER_FORROOT_GUARD');
                                    ^

TypeError: __WEBPACK_IMPORTED_MODULE_0__angular_core__.OpaqueToken is not a constructor
    at Object.module.exports (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:692:37)
    at __webpack_require__ (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:30:30)
    at Object.<anonymous> (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:260:82)
    at __webpack_require__ (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:30:30)
    at Object.module.exports (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:98:82)
    at __webpack_require__ (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:30:30)
    at Object.module.exports (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:961:83)
    at __webpack_require__ (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:30:30)
    at Object.<anonymous> (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:930:86)
    at __webpack_require__ (/node_modules/localize-router-http-loader/bundles/http-loader.umd.js:30:30)

```

As I currently can use the ManualParserLoader it isn't that big of an issue, but nonetheless would it be nice to make it compatible.

Thanks for your awesome work

**Comment by meeroslav** [comment]
@Chuvisco88, can you tell me which version of `localize-router` you are using?

This problem should be fixed in the latest version `1.0.0-rc.3`.

**Comment by Chuvisco88** [comment]
Hmmm strange, I double checked and I am already using `1.0.0-rc.3`

EDIT: I did a quick search for `OpaqueToken` in both node_module folders (`localize-router` and `localize-router-http-loader`).
There was 1 occurence in `localize-router` (`MIGRATION_GUIDE.md`) and several occurences in `localize-router-http-loader` (most in `http-loader.umd.js`).

So I guess the issue is in `localize-router-http-loader`, but you have better insights on that.

**Comment by meeroslav** [comment]
Okay, thanks for letting me know... then I need to rollout the new version. Probably was mistakenly deployed with old package still in place.

**Comment by prvn3294** [comment]
@meeroslav , Is there any update on this issue ? 
I am also facing same issue while using it with angular universal.

**Comment by sarath704** [comment]
+1 

Is there any update on this issue ?

**Comment by liyunfei0302** [comment]
+1

**Comment by elSuperRiton** [comment]
+1

**Comment by markelor** [comment]
+1

**Comment by ninjashare** [comment]
+1

**Comment by meeroslav** [comment]
Hi, the new version has been published. 
I'm waiting for the access in order to merge it back to this branch.

Sorry for waiting
